services:
  - type: worker
    name: NFO-SCALPING
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CLIENT_ID
        sync: true
      - key: ACCESS_TOKEN
        sync: true
      - key: APP_NAME
        sync: true
