services:
  - type: worker
    name: NFO-SCALPING
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CLIENT_ID
        fromEnv: CLIENT_ID
      - key: ACCESS_TOKEN
        fromEnv: ACCESS_TOKEN
      - key: APP_NAME
        fromEnv: APP_NAME
